apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-ilm-policy
  namespace: elastic-stack
data:
  policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "actions": {}
          },
          "delete": {
            "min_age": "2d",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }
