apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tempo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
